#!/usr/bin/env python

STATUS_NODE_NO_ERROR            = 1
STATUS_NODE_ERROR               = 0

STATUS_VREP_WAITING_4_CMD       = 0
STATUS_VREP_IN_PROGRESS         = 1
STATUS_VREP_READY               = 2

PROCESSING_MODE_WRITING         = 0
PROCESSING_MODE_LOGO            = 1
PROCESSING_MODE_PTP_POSITION    = 2
PROCESSING_MODE_PTP_ANGLES      = 3
PROCESSING_MODE_LIN_POSITION    = 4
PROCESSING_MODE_LIN_ANGLES      = 5