#!/usr/bin/env python2

import sys

#from rqt_bag.bag import Bag
from rqt_gui.main import Main

plugin = 'youbot_rw_rqt_gui.my_module.YouBotGui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
